subdomains:
- subdomain: torrent
  target: 192.168.50.168:9090
  schema: http
# - subdomain: music
#   target: 127.0.0.1:32400
#   schema: http
# - subdomain: node
#   target: 127.0.0.1:9100
#   schema: http
- subdomain: anime
  target: 127.0.0.1:5321
  schema: http
- subdomain: home
  target: 127.0.0.1:8123
  schema: http
- subdomain: pihole
  target: 127.0.0.1:81
  schema: http
- subdomain: mqtt
  target: 127.0.0.1:9001
  schema: http
- subdomain: public
  target: 127.0.0.1:8123
  schema: http
- subdomain: public-mqtt
  target: 127.0.0.1:9001
  schema: http
- subdomain: ma
  target: 127.0.0.1:8095
  schema: http
- subdomain: router
  target: 192.168.50.1:8443
  schema: https

services_path: /var/services
ssl_path: /etc/nginx/ssl/

gcp_project: clicia-iot-281611

home_assistant_config_dir: /var/services/home-assistant
docker_compose_dir: /var/services/home-assistant
home_assistant_backup_server: 192.168.50.168
