subdomains:
- subdomain: torrent
  target: 192.168.1.6:9090
  schema: http
- subdomain: ir
  target: 127.0.0.1:1880
  schema: http
- subdomain: curtain
  target: 127.0.0.1:5322
  schema: http
- subdomain: webaccess
  target: 192.168.1.6:9000
  schema: https
- subdomain: music
  target: 127.0.0.1:32400
  schema: http
- subdomain: node
  target: 127.0.0.1:9100
  schema: http
- subdomain: anime
  target: 127.0.0.1:5321
  schema: http
- subdomain: home
  target: 127.0.0.1:8123
  schema: http
- subdomain: pihole
  target: 127.0.0.1:81
  schema: http
- subdomain: mqtt
  target: 127.0.0.1:9001
  schema: http
- subdomain: public
  target: 127.0.0.1:8123
  schema: http
- subdomain: public-mqtt
  target: 127.0.0.1:9001
  schema: http
- subdomain: ma
  target: 127.0.0.1:8095
  schema: http

services_path: /var/services
ssl_path: /etc/nginx/ssl/

gcp_project: clicia-iot-281611

home_assistant_config_dir: /var/services/home-assistant
docker_compose_dir: /var/services/home-assistant
home_assistant_backup_server: 192.168.1.6
