- name: Install Package
  apt:
    pkg:
      - nginx
    state: present

- name: Disable default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy Nginx config
  copy:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: Copy proxy config
  template:
    src: etc/nginx/sites-enabled/inlets.conf
    dest: /etc/nginx/sites-enabled/inlets_{{ domain.subdomain }}.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
  with_items: "{{ domains }}"
  loop_control:
    loop_var: domain

- name: start nginx
  become: true
  systemd:
    name: nginx
    state: started
    enabled: yes
