- name: Create group nginx
  group:
    name: nginx
    state: present

- name: Create user nginx
  user:
    name: nginx
    group: nginx
    state: present

- name: Update Package
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Package
  apt:
    pkg:
    - nginx
    state: latest

- name: Disable default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy Nginx config
  copy:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: 0644
  notify: reload nginx

- name: Copy proxy config
  template:
    src: etc/nginx/sites-enabled/site.conf.j2
    dest: /etc/nginx/sites-enabled/{{ item.subdomain }}.conf
    owner: nginx
    group: nginx
    mode: 0644
  notify: reload nginx
  with_items: "{{ subdomains }}"
  loop_control:
    loop_var: item

- name: start nginx
  become: true
  systemd:
    name: nginx
    state: started
    enabled: yes
