---
- hosts: pi
  vars:
    target_domains: "{{ [domains.v4, domains.v6] }}"
    inlets_type: client
  roles:
  - name: ir-control-node
    become: true
    tags:
    - services
    - ir
  - name: anime-fetcher
    become: true
    tags:
    - services
    - anime-fetcher
  - role: lets-encrypt
    become: true
    tags:
    - ssl
    - lets-encrypt
  - role: nginx
    become: true
    tags:
    - ssl
    - nginx
  - role: home-assistant
    become: true
    tags:
    - home-assistant
    - ha
  - name: pihole
    tags:
    - pihole
  - role: serveo
    become: true
    tags:
    - serveo
  # - role: plexmediaserver
  #   become: true
  #   tags:
  #   - plex
