---
- hosts: pi
  roles:
  - name: nodejs
    tags:
    - nodejs
  - name: ir-control-node
    become: true
    tags:
    - services
    - ir
  - name: pihole
    tags:
    - pihole
  - name: golang
    tags:
    - golang
  - role: lets-encrypt
    become: true
    tags:
    - ssl
    - lets-encrypt
  - role: nginx
    become: true
    tags:
    - ssl
    - nginx
  - role: plexmediaserver
    become: true
    tags:
    - plexmediaserver

