---
- hosts: pi
  vars:
    target_domains: "{{ [domains.v4, domains.v6] }}"
  roles:
  - name: nodejs
    tags:
    - nodejs
  - name: ir-control-node
    become: true
    tags:
    - services
    - ir
  - name: pihole
    tags:
    - pihole
  - name: golang
    tags:
    - golang
  - role: lets-encrypt
    become: true
    tags:
    - ssl
    - lets-encrypt
  - role: nginx
    become: true
    tags:
    - ssl
    - nginx
  - role: plexmediaserver
    become: true
    tags:
    - plexmediaserver
  - role: ansible-role-docker-master
    become: true
    tags:
    - docker
  - name: mornin
    become: true
    tags:
    - services
    - mornin
  - name: node_exporter
    become: true
    tags:
    - monitoring

