---
- name: APT_KEY | Remove dev2day PMS key (legacy)
  apt_key:
    id: 6E44829202F4E6DF0C92525397BC9498DC9666A8
    url: https://dev2day.de/pms/dev2day-pms.gpg.key
    state: absent

- name: APT_REPOSITORY | Remove dev2day PMS repo (legacy)
  apt_repository:
    repo: deb https://dev2day.de/pms/ jessie main
    state: absent
  register: pms_repo_added

- name: APT_KEY | Add official PMS key
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: APT_REPOSITORY | Add official PMS repo
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present
  register: pms_repo_added

- name: APT | Update
  apt:
    update_cache: yes
  when: pms_repo_added.changed

- name: APT | Install plexmediaserver
  apt:
    name: plexmediaserver
    state: latest
  register: plexmediaserver_installed

- name: Install samba client
  apt:
    pkg:
    - samba-common
    - smbclient
    - samba-common-bin
    - smbclient
    - cifs-utils
    state: latest

- name: Mount server
  mount:
    path: /mnt/nas
    src: //{{ services.plex.smb_server }}/share
    fstype: cifs
    state: mounted
    opts: username=guest,password="",vers=1.0

- name: SERVICE | Restart plexmediaserver
  service:
    name: plexmediaserver
    state: restarted
  when: plexmediaserver_installed.changed
