- name: Copy binary tunnel {{ domain.subdomain }}
  template:
    src: inlets
    dest: /usr/local/bin/inlets_{{ domain.subdomain }}
    mode: 0755
    owner: root
    group: root
  notify:
    - Restart all tunnels

- name: Copy systemd file tunnel {{ domain.subdomain }}
  template:
    src: inlets.service
    dest: /etc/systemd/system/inlets_{{ domain.subdomain }}.service
    owner: root
    group: root
  notify:
    - Restart all tunnels

- name: Enable tunnel {{ domain.subdomain }}
  systemd:
    name: inlets_{{ domain.subdomain }}
    state: started
    enabled: yes
