---
- name: Check {{ item }} Version
  shell: "{{ user_shell.command }} \"which {{ item }}\""
  register: item_path

- name: Link {{ item }}
  file:
    src: "{{ item_path.stdout }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  become: true