- name: Install via git
  git:
    dest: "{{ services_path }}/ir-control-node"
    repo: 'https://github.com/yuyuvn/ir-control-node'
    force: yes
  notify:
    - Restart IR control service

- name: Install nodejs and npm
  apt:
    name: 
      - nodejs
      - npm
    state: present

- name: Install node modules
  npm:
    path: "{{ services_path }}/ir-control-node"
    state: present

- name: Copy binary IR control node
  template:
    src: ir-control-node
    dest: /usr/local/bin/ir-control-node
    mode: 0755
    owner: root
    group: root
  notify:
    - Restart IR control service

- name: Copy systemd IR control node
  template:
    src: ir-control-node.service
    dest: /etc/systemd/system/ir-control-node.service
    owner: root
    group: root
  notify:
    - Restart IR control service

- name: Enable IR control node
  systemd:
    name: ir-control-node
    state: started
    enabled: yes
