- name: Copy systemd mornin-plus-node-controll
  template:
    src: mornin-plus-node-controll.service
    dest: /etc/systemd/system/mornin-plus-node-controll.service
    owner: root
    group: root
  notify:
    - Restart mornin

- name: Enable mornin-plus-node-controll
  systemd:
    name: mornin-plus-node-controll
    state: started
    enabled: yes
