# Pi-hole configuration directory
pihole_config_dir: "/opt/pihole"

# Web interface port (default: 81)
pihole_http_port: "81"

# Timezone
timezone: "UTC"

# Upstream DNS servers
pihole_upstream_dns_1: "8.8.8.8"
pihole_upstream_dns_2: "8.8.4.4"

# Docker Compose version
docker_compose_version: "2.17.2"
