---
- name: Install Docker and Docker Compose
  ansible.builtin.apt:
    name:
      - docker
      - docker-compose
    state: present
    update_cache: yes
  become: true

- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ pihole_config_dir }}"
    - "{{ pihole_config_dir }}/etc-pihole"
    - "{{ pihole_config_dir }}/etc-dnsmasq.d"
  become: true

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ pihole_config_dir }}/docker-compose.yml"
    mode: '0644'
  register: compose_file
  become: true

- name: Copy systemd service file
  ansible.builtin.template:
    src: pihole.service.j2
    dest: /etc/systemd/system/pihole.service
    mode: '0644'
  become: true
  register: service_file

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true
  when: service_file.changed

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Enable and start Pi-hole service
  ansible.builtin.systemd:
    name: pihole
    state: started
    enabled: yes
  become: true
